image: "golang:1.13"

before_script:
  - git clone https://github.com/katzenpost/memspool
  - cd memspool/server/cmd/memspool
  - go install
  - cd /builds/katzenpost/kimchi/

kimchi:
  script:
    - go test -v -cover -race  ./...
