image: "golang:1.13"

before_script:
  - git clone https://github.com/katzenpost/memspool
  - cd memspool/server/cmd/memspool
  - go install
  - cd /builds/katzenpost/kimchi/

kimchi:
  script:
    - mkdir -p coverage
    - go test -v -cover -coverprofile cover.out -covermode atomic -race  ./...
    - go tool cover -html=cover.out -o coverage/coverage.html
  artifacts:
    paths:
      - coverage/
